### ISSUE TITLE
Where to intercept the dev env warnings?

### ISSUE THREAD

**Issue by kobe-ra** [westacks/inertia-svelte#2]
hi, i believe we all are receiving these warnings:

![image](https://github.com/westacks/inertia-svelte/assets/32091524/e23c69f0-5367-46c7-a5c1-a00e7a36355d)

i've been trying to catch them at some places in this package so we could create a setting at createInertiaApp function, where user would list their specific warnings and they would've been disabled for dev env. well, they are not present in prod env anyway.

if you have idea where could these be intercepted, please let me know and i'd make a pr.

i did something similar with ziggy's routes which svelte compiler doesnt like, because they are undefined. solved in `vite.config.js` like this:

```
svelte({
    onwarn: (warning, handler) => {
        if (warning.message.includes("'route' is not defined")) return;
        handler(warning);
    },
}),
```

**Comment by punyflash** [comment]
Refer to sveltejs/svelte#4652. Currently, there is no way inside svelte compiler to omit these errors. And to be honest, a lot of devs thinks they are annoying, but I think they are quite helpful. They not end up in production after app build, so I don't see them cause any trouble. Just ignore them if you do not need to use those props.
