### ISSUE TITLE
[v2.0] - ERR_SVELTE_HYDRATION_MISMATCH: Hydration failed because the initial UI does not match what was rendered on the server

### ISSUE THREAD

**Issue by harryqt** [westacks/inertia-svelte#5]
Can't make Svelte 5 and `@westacks/inertia-svelte@next` work together. After running `bun run dev`, I am getting errors.
Also made a repo: [Dibbyo456/westack-svelte-bug-report](https://github.com/Dibbyo456/westack-svelte-bug-report)

<img width="1582" alt="Screenshot 2024-03-28 at 4 50 10 PM" src="https://github.com/westacks/inertia-svelte/assets/18257605/a58e86e2-a8b2-4482-86e0-55cf21a3c344">

**Comment by harryqt** [comment]
If i use `mount(App, { target: el, props });` instead `hydrate(App, { target: el, props });` then everything works, but breaks ssr. On ssr mode content renders twice. @punyflash

**Comment by punyflash** [comment]
You don't have SSR build in your example repo. You can't hydrate if there is no HTML

**Comment by harryqt** [comment]
I have added commit for ssr in the repo. Basically on `app.js`:

```js
    setup({ el, App, props }) {
        // using this shows hydration error when using 'npm run dev', but ssr works.
        hydrate(App, {target: el, props})

        // using this works, but content renders twice in ssr mode.
        // mount(App, {target: el, props})
    }
```

**Comment by punyflash** [comment]
![image](https://github.com/westacks/inertia-svelte/assets/14828695/494b157b-3834-4d5d-81a3-8f9c4aa7ed90)
It works with SSR. The issue in current Svelte 5 hydration behavior, as it doesn't render contents if there is no markup from server. You should report it in [sveltejs/svelte](https://github.com/sveltejs/svelte) directly. Svelte 5 currently not released yet, so this is may be changed after initial release

**Comment by harryqt** [comment]
> It works with SSR.

Yes, works only with SSR but on `npm run dev` does not work. - https://drive.google.com/file/d/1jpAO-HcsLCM7NKxrcfIdlGGtpueXczsD/view

> The issue in current Svelte 5 hydration behavior, as it doesn't render contents if there is no markup from server.

You could be right, according to Svelte 5 [docs](https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes): 

> In Svelte 3 and 4, components are classes. In Svelte 5 they are functions and should be instantiated differently. If you need to manually instantiate components, you should use `mount` or `hydrate` (imported from `svelte`) instead. `mount` and `hydrate` have the exact same API. The difference is that `hydrate` will pick up the Svelte's server-rendered HTML inside its target and hydrate it.

Maybe on `hydrate` method svelte expecting a server-rendered HTML?

**Comment by punyflash** [comment]
For now, you can manually check if server rendered content is present on the page, as [SSR](https://github.com/westacks/inertia-svelte/blob/f49214bfaf0a5c20b9a0e61d2b16683a71cc29e2/src/lib/components/SSR.svelte#L9C6-L9C33) component sets `data-server-rendered="true"` attribute on the app element. So your code should look something like this (not tested it):

```js
// app.js

import { createInertiaApp } from '@westacks/inertia-svelte'
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers'
import { hydrate, mount } from 'svelte'

createInertiaApp({
    resolve: name => resolvePageComponent(`./pages/${name}.svelte`, import.meta.glob('./pages/**/*.svelte')),
    setup({ el, App, props }) {
        const h = el.dataset?.serverRendered ? hydrate : mount
        h(App, {target: el, props})
    }
})
```

**Comment by harryqt** [comment]
It works, thank you so much.
