### ISSUE TITLE
useForm error on esmodule due to lodash import

### ISSUE THREAD

**Issue by axmad386** [westacks/inertia-svelte#7]
Hi, thanks for this great library. I use it on pure esm project, then this error happens when I use `useForm`
```
import { cloneDeep, isEqual } from "lodash";
         ^^^^^^^^^
SyntaxError: Named export 'cloneDeep' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named 
exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { cloneDeep, isEqual } = pkg;

```

This due to lodash actually cjs module so cannot be imported like that. This issue can be solved by import lodash as default (but is not recomended.
```
import lodash from "lodash";
const { cloneDeep, isEqual } = lodash;
```
Or change the dependencies from lodash to [lodash.clonedeep](https://www.npmjs.com/package/lodash.clonedeep) and [lodash.isequal](https://www.npmjs.com/package/lodash.isequal) separately.
This issue occure on v1 and v2.

**Comment by punyflash** [comment]
Thanks for reporting. Not a fan adding multiple dependencies, just imported methods from separate files:
```js
import cloneDeep from 'lodash/cloneDeep';
import isEqual from 'lodash/isEqual';
```

This should also benefit package size a little. Fixed in version `1.0.29` and `2.0.0-next.3`
