### ISSUE TITLE
How to use tanstack-query with this?

### ISSUE THREAD

**Issue by shininglove** [westacks/inertia-svelte#9]
I tried to add tanstack-query to my app, but it kept complaining that I didn't have the provider. It seems I would need to wrap the app managed by this plugin in the query provider. How would I do that?

**Comment by punyflash** [comment]
Overall, Inertia is not really flexible for that task. I think you could use persistent layout to wrap your app in query client:

### `./layouts/TanStack.svelte`:
```svelte
<script lang="ts">
  import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query'

  const queryClient = new QueryClient()
</script>

<QueryClientProvider client={queryClient}>
  <slot/>
</QueryClientProvider>
```

### `app.ts`:
```ts
import { createInertiaApp } from '@westacks/inertia-svelte'
import { TanStack } from './layouts/TanStack.svelte'

createInertiaApp({
  resolve: name => {
    const page = import.meta.glob('./Pages/**/*.svelte', { eager: true })[`./Pages/${name}.svelte`]
    page.layout = page.layout
        ? (Array.isArray(page.layout) ? [TanStack, ...page.layout] : [TanStack, page.layout])
        : [TanStack]

    return page
  },
  setup({ el, App, props }) {
    new App({ target: el, props })
  },
})

**Comment by shininglove** [comment]
@punyflash thanks for the reply! for some reason when I try this out it says layout is read-only and I haven't been able to see a work-around yet.

**Comment by punyflash** [comment]
> @punyflash thanks for the reply! for some reason when I try this out it says layout is read-only and I haven't been able to see a work-around yet.

Are you using `const` in page components when defining layout?

**Comment by shininglove** [comment]
> > @punyflash thanks for the reply! for some reason when I try this out it says layout is read-only and I haven't been able to see a work-around yet.
> 
> Are you using `const` in page components when defining layout?

I don't believe so, here is the code I'm trying: https://github.com/bonchondev/job-scheduler/blob/svelte-query/views/main.js

**Comment by shininglove** [comment]
I think this probably doesn't have to your package, I can use tanstack with vue, and see if Svelte 5 makes this easier or something like that. Thanks for responding!

**Comment by shininglove** [comment]
finally figured it out after looking at the inertia-django repo, for some reason this works

```js
resolve: (name) => {
    const allPages = import.meta.glob('./src/**/*.svelte', { eager: true })
    const page = allPages[`./src/pages/${name}.svelte`];
    return { default: page.default, layout: page.layout || Tanstack }
  },

```
